apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: kubeflow
  name: kubeflow
spec:
  containers:
  - image: kubeflow
    name: kubeflow
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
